# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       xkeyboard-config

# >> macros
# << macros

Summary:    Alternative xkb data files
Version:    2.5.1
Release:    1
Group:      System/X11
License:    MIT
BuildArch:  noarch
URL:        http://www.freedesktop.org/wiki/Software/XKeyboardConfig#Releases
Source0:    http://xorg.freedesktop.org/archive/individual/data/%{name}-%{version}.tar.bz2
Source100:  xkeyboard-config.yaml
Patch0:     fix-rx51-enter.patch
Patch1:     n950-support.patch
Patch2:     n950-makefile.in-manual-fix.patch
Patch3:     n810-support.patch
BuildRequires:  pkgconfig(xorg-macros)
BuildRequires:  pkgconfig
BuildRequires:  xkbcomp
BuildRequires:  perl(XML::Parser)
BuildRequires:  gettext
BuildRequires:  intltool
BuildRequires:  fdupes
Provides:   xkbdata
Obsoletes:   xorg-x11-xkbdata

%description
Alternative xkb data files.

%package devel
Summary:    Devel package for alternative xkb data files
Group:      System/X11
Requires:   %{name} = %{version}-%{release}

%description devel
Development files for %{name}.


%prep
%setup -q -n %{name}-%{version}

# fix-rx51-enter.patch
%patch0 -p1
# n950-support.patch
%patch1 -p1
# n950-makefile.in-manual-fix.patch
%patch2 -p1
# n810-support.patch
%patch3 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --enable-compat-rules \
    --with-xkb-base=%{_datadir}/X11/xkb \
    --disable-xkbcomp-symlink \
    --with-xkb-rules-symlink=xorg \
    --disable-runtime-deps

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre

# << install pre
%make_install

# >> install post
# Remove unnecessary symlink
rm -f $RPM_BUILD_ROOT%{_datadir}/X11/xkb/compiled

# Bernie: remove locale stuff
rm -rf $RPM_BUILD_ROOT%{_datadir}/locale

# Create filelist
{
FILESLIST=${PWD}/files.list
pushd $RPM_BUILD_ROOT
find ./usr/share/X11 -type d | sed -e "s/^\./%dir /g" > $FILESLIST
find ./usr/share/X11 -type f | sed -e "s/^\.//g" >> $FILESLIST
popd
}


# << install post

%fdupes  %{buildroot}//usr/share/X11

%files -f files.list
%defattr(-,root,root,-)
# >> files
%{_datadir}/X11/xkb/rules/xorg
%{_datadir}/X11/xkb/rules/xorg.lst
%{_datadir}/X11/xkb/rules/xorg.xml
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%{_datadir}/pkgconfig/xkeyboard-config.pc
# << files devel
